/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as MarketRouteImport } from './routes/market'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairSymbolRouteImport } from './routes/pair.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairSymbolRoute = PairSymbolRouteImport.update({
  id: '/pair/$symbol',
  path: '/pair/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/journal': typeof JournalRoute
  '/market': typeof MarketRoute
  '/settings': typeof SettingsRoute
  '/pair/$symbol': typeof PairSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/journal': typeof JournalRoute
  '/market': typeof MarketRoute
  '/settings': typeof SettingsRoute
  '/pair/$symbol': typeof PairSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/journal': typeof JournalRoute
  '/market': typeof MarketRoute
  '/settings': typeof SettingsRoute
  '/pair/$symbol': typeof PairSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/chat' | '/journal' | '/market' | '/settings' | '/pair/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat' | '/journal' | '/market' | '/settings' | '/pair/$symbol'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/journal'
    | '/market'
    | '/settings'
    | '/pair/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  JournalRoute: typeof JournalRoute
  MarketRoute: typeof MarketRoute
  SettingsRoute: typeof SettingsRoute
  PairSymbolRoute: typeof PairSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair/$symbol': {
      id: '/pair/$symbol'
      path: '/pair/$symbol'
      fullPath: '/pair/$symbol'
      preLoaderRoute: typeof PairSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  JournalRoute: JournalRoute,
  MarketRoute: MarketRoute,
  SettingsRoute: SettingsRoute,
  PairSymbolRoute: PairSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
